database:
  name: study
server:
  port: 8081
  http2:
    enabled: true
  kafka:
    consumer:
      group-id: kafka-intro
      bootstrap-servers:
      - localhost:9092
      
#spring:
#  config:
#    location: classpath:/config